language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm

matrix:
  allow_failures:
    - php: [nightly, hhvm]

before_install:
  - composer self-update

install:
  - composer install -o --dev --prefer-source

script: phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
